rm(list=ls())

#nematode that adaptations to evade the immune response of one species are no good against the immune response of another species.  

library(ggplot2)

thymus<-read.table(file.choose(),header=TRUE)


str(thymus)#will bring up a summary of the data with the sample size and what type of data it thinks each column is.
names(thymus)#gives you a list of the names of the variables in your file.

# fitting  a two factor GLM 
mymodel <- lm(day10~species+status+species*status, data=thymus)
anova(mymodel)

#interpretting anova
#species has an affect on worms at day 10 
#status has an affect on worms at day 10
#the effects of species and status do depend on each other  


#generating an interaction plot
#step 1. generate a summary table of the means of the 4 combinations of species and thymic status. 
summ <- aggregate(day10~species+status, thymus, mean) #uses the aggregate function to calculate the means we need and store it in an object called sum. 
summ

#use ggplot2 to produce a nice graphic of this
ggplot(summ, aes(x=species, y=day10, colour=status, group=status)) +
  geom_point() +
  geom_line() +
  theme_bw()

#interpretting the graph produced 
#species seems to be having the greatest effect 
#there is an interaction between thymic status and species

#hypothesis:
#host immune system was responsible for host specificity,
#the worm should do much worse in normal mice than in normal rats,
#but in immune-deficient hosts of either species, the performance of the worms should be similar


#assumptions:
par(mfrow=c(2,2)) 
plot(mymodel)
par(mfrow=c(1,1)) 
#there are violations..
#there isnt homogeneity of variance and there isnt normality in data  
#maybe due to  small sample size - larger relative amount of random variation so doesnt fit a normal distribution?

#to deal with the problem with our assumptions we will try transforming our data
#Transformations always require a degree of trial and error, 
#so let’s use a square root transformation as our first trial

thymus <- cbind(thymus, sqrt(thymus$day10) ) #This creates a new column in our data set which contains the squareroots of the data in the day 10 column. 
#create a new dataset by combining (cbind) the thymus dataset with a column of data that is generated by square root transforming the data in the day10 column of the thymus file,
#and then give this new combined object the same name as the original data file (i.e. replacing the original thymus dataset with the new thymus dataset). 

#run an additional line of code to change the name of the column to something more manageable
names(thymus)[names(thymus)=="sqrt(thymus$day10)"] <- "sqrtday10"


#fitting new model to see if this transformation has helped
mymodel2 <- lm(sqrtday10~species+status+species*status, data=thymus)
anova(mymodel2)
par(mfrow=c(2,2)) 
plot(mymodel2)
par(mfrow=c(1,1)) 

#didnt help much

#transforming into log10
#new column with log10
thymus <- cbind(thymus, log10(thymus$day10) )
names(thymus)[names(thymus)=="log10(thymus$day10)"] <- "logday10"
mymodel3 <- lm(logday10~species+status+species*status, data=thymus)
anova(mymodel3)
par(mfrow=c(2,2)) 
plot(mymodel3)
par(mfrow=c(1,1)) 
#homogeneity assumption met
#normality assumption met


#generating an interaction plot
#step 1. generate a summary table of the means of the 4 combinations of species and thymic status. 
summ3 <- aggregate(logday10~species+status, thymus, mean) #uses the aggregate function to calculate the means we need and store it in an object called sum. 
summ3

#use ggplot2 to produce a nice graphic of this
ggplot(summ3, aes(x=species, y=logday10, colour=status, group=status)) +
  geom_point() +
  geom_line() +
  theme_bw()

#hypothesis again..
#if there is a difference bc of immune system if we knock out immune system it would show no change 
#prediction is there is an interaction

#What do you conclude about the original hypothesis?
#both species and status effect worm burden on day 10
#interaction between species and status has no effect 
#unlike first model which looked like interactino did have an effect

#Why are your results different from those from the original model?
#the results are different because the model now used meets the assumptions where as the first model did not meet the assuptions of homogeneity of variance and normality

#How much of the variation in Log10 worm numbers does your general linear model explain?
#explained variation can be calculated from additing SS of the predictors and subtract residual SS 
#or use the summary my model function and the multiple R-squared value tells you the proportion of variance explained by the model
#Does this seem a lot or a little?
#the proportion explained by the model is 0.8241 which is alot!! 

summary(mymodel3)
